# Generated by Django 4.2.13 on 2024-07-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="default.jpg", upload_to="profile_images"),
        ),
    ]
